In [2]:
import numpy as np
import pandas as pd

In [3]:
np.__version__

'1.15.4'

In [4]:
pd.__version__

'0.23.4'

In [6]:
wget raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

SyntaxError: invalid syntax (<ipython-input-6-0541a0c3226a>, line 1)

In [9]:
dataset = pd.read_csv("cardata.csv")

In [10]:
dataset.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
dataset.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [12]:
dataset.groupby('Make').mean()

Year    Engine HP  Engine Cylinders  Number of Doors  \
Make                                                                         
Acura          2010.063492   244.797619          5.333333         3.619048   
Alfa Romeo     2015.400000   237.000000          4.000000         2.000000   
Aston Martin   2013.021505   484.322581         10.623656         2.150538   
Audi           2012.231707   277.695122          5.557927         3.469512   
BMW            2014.347305   326.907186          5.958084         3.161677   
Bentley        2011.702703   533.851351          9.729730         2.675676   
Bugatti        2008.333333  1001.000000         16.000000         2.000000   
Buick          2010.005102   219.244898          5.316327         3.836735   
Cadillac       2013.151134   332.309824          6.433249         3.602015   
Chevrolet      2010.087266   246.972247          5.908118         3.381122   
Chrysler       2008.459893   229.139037          5.593583         3.625668   
Dodge          2005.440895   244.415335          6.258786         3.210863   
FIAT           2016.032258   143.559322          3.806452         2.903226   
Ferrari        2007.521739   511.956522          9.797101         2.000000   
Ford           2009.741203   243.097926          5.914869         3.383655   
GMC            2009.126214   259.844660          6.454369         3.495146   
Genesis        2017.000000   347.333333          6.666667         4.000000   
HUMMER         2009.352941   261.235294          6.058824         4.000000   
Honda          2013.418708   195.749441          4.659243         3.536748   
Hyundai        2012.696370   201.917492          4.666667         3.498350   
Infiniti       2010.960606   310.066667          6.151515         3.545455   
Kia            2013.614719   206.827434          4.588745         3.939394   
Lamborghini    2012.730769   614.076923         10.884615         2.000000   
Land Rover     2012.671329   322.097902          6.125874         3.790210   
Lexus          2011.623762   277.415842          6.247525         3.712871   
Lincoln        2011.573171   284.910256          6.073171         3.853659   
Lotus          2010.827586   275.965517          5.241379         2.000000   
Maserati       2012.775862   420.793103          7.344828         2.793103   
Maybach        2010.937500   590.500000         12.000000         4.000000   
Mazda          2008.364066   171.992908          4.615385         3.460993   
McLaren        2014.200000   610.400000          8.000000         2.000000   
Mercedes-Benz  2010.515581   350.181818          6.711048         3.351275   
Mitsubishi     2009.164319   173.429245          4.680952         3.596244   
Nissan         2012.403226   239.921533          5.336918         3.433692   
Oldsmobile     1997.613333   177.466667          5.573333         3.573333   
Plymouth       1995.463415   131.560976          4.390244         3.207317   
Pontiac        2003.102151   190.295699          5.483871         3.193548   
Porsche        2013.382353   392.794118          6.132353         2.647059   
Rolls-Royce    2012.516129   487.548387         11.870968         3.290323   
Saab           2006.081081   220.522523          4.540541         3.477477   
Scion          2013.416667   154.433333          4.000000         3.000000   
Spyker         2009.000000   400.000000          8.000000         2.000000   
Subaru         2011.246094   197.308594          4.367188         3.773438   
Suzuki         2006.310541   160.287749          4.547009         3.823362   
Tesla          2015.277778          NaN          0.000000         4.000000   
Toyota         2012.544236   236.147849          5.597315         3.592493   
Volkswagen     2012.812114   189.757726          4.365217         3.222497   
Volvo          2008.060498   230.971530          4.722420         3.914591   

               highway MPG   city mpg  Popularity          MSRP  
Make                                                   

In [28]:
df = dataset[dataset['Year']>= 2015]
df.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [29]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [30]:
mean_hp_before = df['Engine HP'].mean()
print(round(mean_hp_before))

273


In [31]:
df2 = df.fillna(mean_hp_before)

In [32]:
mean_hp_after = df2['Engine HP'].mean()
print(round(mean_hp_after))

273


In [34]:
dfr = dataset[dataset['Make'] == 'Rolls-Royce']
dfr.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [36]:
dfru = dfr.drop(['Make','Model','Year','Engine Fuel Type','Transmission Type','Driven_Wheels','Number of Doors','Market Category','Vehicle Size','Vehicle Style','city mpg','Popularity','MSRP'], axis=1)

In [37]:
dfru.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [39]:
dfru1 = dfru.drop_duplicates()
dfru1.head(10)

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [40]:
x = np.array(dfru1)

In [41]:
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [42]:
x2 = x.transpose()
x2

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [45]:
xtx = np.matmul(x2,x)

In [46]:
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [47]:
invx = np.linalg.inv(xtx)
invx

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [48]:
np.sum(invx)

0.032212320677486195

In [49]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [50]:
m1 = np.matmul(invx,x2)
m1

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [52]:
w = np.matmul(m1,y)
w

array([ 0.19989598, 31.02612262, 31.65378877])